#url: http://www.manoamaro.com.br
url: http://localhost:4000
sitemap:
  file: "/sitemap.xml"
  exclude:
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

highlighter: rouge
