---
title: Manoamaro.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://www.manoamaro.com.br
gems:
- jekyll-sitemap
- jekyll-coffeescript
